version: '3.8'

services:
  getty-search:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: getty-search
    ports:
      - "8000:8000"
    volumes:
      - ./cache:/app/cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 